# Generated by Django 5.2.5 on 2025-08-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video_converted_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080p/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_converted_360p',
            field=models.FileField(blank=True, null=True, upload_to='videos/360p/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_converted_480p',
            field=models.FileField(blank=True, null=True, upload_to='videos/480p/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_converted_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(upload_to='videos/originals/'),
        ),
    ]
