# Generated by Django 5.2.5 on 2025-08-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_movie_video_converted_1080p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='hls_playlist',
            field=models.FileField(blank=True, null=True, upload_to='videos/hls/'),
        ),
    ]
