# Generated by Django 5.2.5 on 2025-08-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_alter_movie_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='hls_playlist',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_converted_1080p',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_converted_360p',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_converted_480p',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_converted_720p',
        ),
        migrations.AddField(
            model_name='movie',
            name='hls_master_playlist',
            field=models.FileField(blank=True, null=True, upload_to='videos/hls_master/'),
        ),
    ]
